FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    iproute2 \
    iputils-ping \
    procps \
    htop \
    sudo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work/AESO

CMD ["bash"]
